import os
import base64
import hashlib
import hmac

PBKDF2_ITERATIONS = 100_000
SALT_SIZE = 16


def hash_password(password: str) -> str:
    """Return a salted PBKDF2 hash for ``password``.

    The returned string is base64 encoded and contains the salt followed by the
    derived key.  It can be stored in an environment variable or config file.
    """
    salt = os.urandom(SALT_SIZE)
    key = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ITERATIONS)
    return base64.b64encode(salt + key).decode()


def verify_password(password: str, hashed: str) -> bool:
    """Check ``password`` against ``hashed`` value generated by :func:`hash_password`.

    Returns ``True`` if the password matches, otherwise ``False``.  An empty
    ``hashed`` value always returns ``False``.
    """
    if not hashed:
        return False
    try:
        data = base64.b64decode(hashed.encode())
    except Exception:
        return False
    salt, key = data[:SALT_SIZE], data[SALT_SIZE:]
    new_key = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ITERATIONS)
    return hmac.compare_digest(new_key, key)
